name: "Unittest Workflow Core"
#on: [workflow_dispatch, push]
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!release_doc'

jobs:
  build:
    runs-on: ubuntu-20.04 #latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    name: Python ${{ matrix.python-version }}
    steps:
      #- name: update OS (Ubuntu)
      #  run: sudo apt-get update
      #- run: sudo apt-get install libudev-dev
      #- run: sudo apt-get install librrd-dev libpython3-dev
      #- run: sudo apt-get install gcc --only-upgrade
      - name: Setup OS (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev
          sudo apt-get install librrd-dev libpython3-dev
          sudo apt-get install gcc --only-upgrade

      - uses: actions/checkout@v2

      - name: Checkout SmartHomeNG CORE DEVELOP Branch
        uses: actions/checkout@v2
        with:
          repository: smarthomeNG/smarthome
          ref: develop
          path: smarthomeng
      - name: Checkout SmartHomeNG plugins DEVELOP Branch
        uses: actions/checkout@v2
        with:
          repository: smarthomeNG/plugins
          ref: develop
          path: smarthomeng/plugins

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python3 -m pip install --upgrade pip #==19.3.1

      - name: Install requirements for unit testing
        run: pip install -r smarthomeng/tests/requirements.txt
      - name: Build Requirements for SmartHomeNG
        run: python3 smarthomeng/tools/build_requirements.py
      - name: Install SmartHomeNG base requirements
        # base requirements are needed for pytest to run
        run: pip install -r smarthomeng/requirements/base.txt

      # ---  up to here, the workflow is identical for CORE and PLUGINS  ---

      - name: Run Python Unittests for CORE
        working-directory: ./smarthomeng/tests
        run: pytest
